### ISSUE TITLE
Upgrade to REEF-0.13

### ISSUE THREAD

**Issue by dongjoon-hyun** [cmssnu/dolphin#138]
Currenlty, our pom.xml file has the following line.

```
<reef.version>0.13.0-incubating-SNAPSHOT</reef.version>
```

But, REEF is moved 0.14.0-incubating-SNAPSHOT already. 
We should move to 0.14-snapshot or official 0.13.

Next week, we will get REEF-0.13 in maven central. After that, this issue propose to upgrade to official REEF-0.13 .

**Comment by jsjason** [comment]
Should we move to 0.14.0-incubating-SNAPSHOT now, then fall back to 0.13.0-incubating after the release is on maven?

**Comment by dongjoon-hyun** [comment]
Thank you, @jsjason , but I think it's also okay for us to wait a week in the current status. :)

**Comment by dongjoon-hyun** [comment]
Hi @jsjason . I made a PR for this, #140 .
