### ISSUE TITLE
Incorrect results of matrix multiplication and matrix concatenation of Nd4j library

### ISSUE THREAD

**Issue by beomyeol** [cmssnu/dolphin#142]
We are using `0.0.3.5.5.5` version of [ND4J](http://nd4j.org/) library for matrix operations. However, I found that matrix multiplication results are incorrect when getting one of operands via `getRow()` method of `INDArray`. `getRow()` method is essential for batch processing.
In addition, the concatenation operation of matrices produces incorrect results of which shapes are wrong. In model partitioning, the concatenation operation is necessary.

With the latest version `0.4-rc3.5` of ND4J, the above issues seem to be fixed. But, multiplication results are still incorrect, which makes `NerualNetworkTest` fail. Although we have watched the updates of ND4J library for more than 2 months, the accuracy problem of matrix multiplication has not been fixed yet.

We may use workarounds for these. But it will make our codes complicated. Thus, we should consider the replacement of ND4J library with other stable, reliable, and faster BLAS libraries such as [JBLAS](http://http://jblas.org/) and [netlib-java](https://github.com/fommil/netlib-java).

**Comment by bgchun** [comment]
+1 on using JBLAS and netlib-java.


On Tue, Nov 3, 2015 at 4:59 PM, Beomyeol Jeon <notifications@github.com>
wrote:

> We are using 0.0.3.5.5.5 version of ND4J <http://nd4j.org/> library for
> matrix operations. However, I found that matrix multiplication results are
> incorrect when getting one of operands via getRow() method of INDArray.
> getRow() method is essential for batch processing.
> In addition, the concatenation operation of matrices produces incorrect
> results of which shapes are wrong. In model partitioning, the concatenation
> operation is necessary.
>
> With the latest version 0.4-rc3.5 of ND4J, the above issues seem to be
> fixed. But, multiplication results are still incorrect, which makes
> NerualNetworkTest fail. Although we have watched the updates of ND4J
> library for more than 2 months, the accuracy problem of matrix
> multiplication has not been fixed yet.
>
> We may use workarounds for these. But it will make our codes complicated.
> Thus, we should consider the replacement of ND4J library with other stable,
> reliable, and faster BLAS libraries such as JBLAS
> <http://http://jblas.org/> and netlib-java
> <https://github.com/fommil/netlib-java>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmssnu/dolphin/issues/142>.
>



-- 
Byung-Gon Chun

**Comment by dongjoon-hyun** [comment]
@swlsw , any comments?

**Comment by swlsw** [comment]
We couldn't find any solution for Nd4j problem, so
+1 on using JBLAS and netlib-java.

**Comment by dongjoon-hyun** [comment]
Very good!
