### ISSUE TITLE
Pooling layer base implementation 

### ISSUE THREAD

**Issue by seyounglee95** [cmssnu/dolphin#161]
In `dolphin-dnn`, CNN has not been implemented yet. We can add general outline for pooling layer as a first step for CNN implementation. This implementation will include a constructor and a `getOutputShape()` function which extends the corresponding abstract function in `LayerBase`. The backpropagate function and feedforward function will be addressed in future issue/PRs.

**Comment by jsjason** [comment]
Closed via #164.
