### ISSUE TITLE
Pooling layer full implementation

### ISSUE THREAD

**Issue by seyounglee95** [cmssnu/dolphin#162]
After pooling layer base implementation issue being resolved, feedforwarding function and  backpropagating function are left to be given shape to. `feedForward()` will resize input matrix using max pooling or average pooling. `backPropagate()` would compute current error using next error. The computation function would be different depending on pooling types. A few matrix computation functions needed to implement two functions above will be added, too.

**Comment by beomyeol** [comment]
Closed via #169
