### ISSUE TITLE
Convolutional layer base implementation

### ISSUE THREAD

**Issue by seyounglee95** [cmssnu/dolphin#166]
CNN implementation is in process. We can add general outline for convolutional layer to take it one step further. This implementation will include a constructor and a `getOutputShape()` function which extends the corresponding abstract function in `LayerBase`.  Configuration settings for convolutional layer will be added, too.  The backpropagate function and feedforward function will be addressed in future issue/PRs.

**Comment by beomyeol** [comment]
Closed via #170.
